export const builderBaseImage = 'public.ecr.aws/eks-distro-build-tooling/builder-base:standard-latest.al2';
export const kubernetesVersions = ['1.27', '1.28', '1.29', '1.30', '1.31', '1.32', '1.33'];
export const betaKubeVersions: Array<string> = [];
export const cnis = ['calico', 'cilium'];
export const eksHybridBetaBucketARN = 'arn:aws:s3:::eks-hybrid-beta';
export const eksReleaseManifestHost = 'hybrid-assets.eks.amazonaws.com';
export const githubRepo = 'eks-hybrid';
export const githubBranch = 'main';
export const requiredEnvVars = ['HYBRID_GITHUB_TOKEN'];
export const clusterVpcCidr = '10.20.0.0/16';
export const clusterPublicSubnetCidr = '10.20.1.0/24';
export const clusterPrivateSubnetCidr = '10.20.2.0/24';
export const hybridVpcCidr = '10.80.0.0/16';
export const hybridPublicSubnetCidr = '10.80.1.0/24';
export const hybridPrivateSubnetCidr = '10.80.2.0/24';
export const hybridPodCidr = '10.87.0.0/16';
export const testClusterTagKey = "Nodeadm-E2E-Tests-Cluster"
export const testClusterPrefix = "nodeadm-e2e-tests"
export const podIdentityS3BucketPrefix = "podid"
